Turn_o_time<-read.csv("C:\\Users\\Anoop Lenka\\Documents\\Downloads\\LabTAT.csv")
View(Turn_o_time)
summary(Turn_o_time)
install.packages("psych")
library(psych)
boxplot(Turn_o_time)
# There is an outlier for Lab 1 and one outlier for lab 4
# Check for normality
hist(Turn_o_time$Laboratory.1)
hist(Turn_o_time$Laboratory.2)
hist(Turn_o_time$Laboratory.3)
hist(Turn_o_time$Laboratory.4)
qqnorm(Turn_o_time$Laboratory.1)
qqline(Turn_o_time$Laboratory.1)
qqnorm(Turn_o_time$Laboratory.2)
qqline(Turn_o_time$Laboratory.2)
qqnorm(Turn_o_time$Laboratory.3)
qqline(Turn_o_time$Laboratory.3)
qqnorm(Turn_o_time$Laboratory.4)
qqline(Turn_o_time$Laboratory.4)
shapiro.test(Turn_o_time$Laboratory.1)
shapiro.test(Turn_o_time$Laboratory.2)
shapiro.test(Turn_o_time$Laboratory.3)
shapiro.test(Turn_o_time$Laboratory.4)
# Equal Variance Test

Lab<-c(rep("Laboratory.1",120),rep("Laboratory.2",120),rep("Laboratory.3",120),rep("Laboratory.4",120))
TAT<-c(Turn_o_time$Laboratory.1,Turn_o_time$Laboratory.2,Turn_o_time$Laboratory.3,Turn_o_time$Laboratory.4)
df<-data.frame(Lab,TAT)
install.packages("car")
library(car)
leveneTest(TAT~ Lab,df)
# One Way ANOVA
TAT.aov<-aov(TAT~Lab, data =df)
summary(TAT.aov)
