customer_order<-read.csv("C:\\Users\\Anoop Lenka\\Documents\\Downloads\\Costomer+OrderForm (2).csv")
View(customer_order)
ctrl<-table(customer_order$Phillippines,customer_order$Indonesia,customer_order$Malta,customer_order$India)
table(customer_order$Phillippines)
table(customer_order$Indonesia)
table(customer_order$Malta)
table(customer_order$India)
country= c(rep("Phillppines", 300), rep("Indonesia", 300), rep("Malta", 300),rep("India",300))
status=c(rep("Defects",113), rep("Error Free", 1087))
finaldata<-read.csv("C:\\Users\\Anoop Lenka\\Documents\\Customer_order.csv")
chisq.test(x=country, y=status,data=finaldata)
