Q1<-read.csv("C:\\Users\\Anoop Lenka\\Documents\\Umesh Lenka-Data Science\\Assignment - Statistics\\Set1Q1.csv")
View(Q1)
install.packages("lattice")
library(lattice)
boxplot(Q1$Measure.X)
mean(Q1$Measure.X)
var(Q1$Measure.X)
sd(Q1$Measure.X)
x <-c(-2000,-1000,0,1000,2000,3000)
sd(x)
